name: Build

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          pip3 install -e .
          pip3 install coverage coveralls mypy pycodestyle pylint
      - name: Test
        run: |
          ./test.sh
        env:
          HMRC_CLIENT_ID: ${{ secrets.HMRC_CLIENT_ID }}
          HMRC_CLIENT_SECRET: ${{ secrets.HMRC_CLIENT_SECRET }}
          HMRC_SERVER_TOKEN: ${{ secrets.HMRC_SERVER_TOKEN }}
      - name: Distribution
        run: |
          python3 setup.py sdist bdist_wheel
      - name: Coverage report
        uses: codecov/codecov-action@v1
      - name: Publish to PyPI
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
